import React from 'react'
import Head from 'next/head'
import { Sidebar } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Whats app</title>
        <meta name="description" content="Generated by Tai Vo" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  )
}
