name: CommitLint CI
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check commit lint 
        uses: wagoid/commitlint-github-action@v5